# Generated by Django 3.0.2 on 2020-01-24 17:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questionPlatform', '0002_remove_answer_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
