# Generated by Django 3.0.2 on 2020-01-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionPlatform', '0003_auto_20200124_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_post_date',
        ),
        migrations.AlterField(
            model_name='question',
            name='post_date',
            field=models.DateTimeField(verbose_name='Post Date'),
        ),
    ]
