# Generated by Django 3.0.2 on 2020-01-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20200122_1733'),
        ('userprofile', '0003_auto_20200123_0554'),
    ]

    operations = [
    ]
